version: "1.0.0"
services:
  reverse-proxy:
    build: ./reverse-proxy
    environment:
      HTTPS: ${HTTPS}
      FRONTEND_DOMAIN_NAME: ${https://netwealthinc4749.pinet.com}
      BACKEND_DOMAIN_NAME: ${https://netwealthinc4749.pinet.com}
      DOMAIN_VALIDATION_KEY: ${https:/netwealthinc4749.pinet.com/7dc673a259e1b20ea6c14f31b6c2b5f39859c7c2a36d97e33bfe6804167bf3b34836a208866d196c843c32c817e86d8c7c655a7fbeb06d8192965b6518947c9b}
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATA_DIRECTORY}/reverse-proxy/etc-letsencrypt:/etc/letsencrypt/

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: ${BACKEND_URL}

  backend:
    build: ./backend
    environment:
      NODE_ENV: ${ENVIRONMENT}
      SESSION_SECRET: ${SESSION_SECRET}
      PI_API_KEY: ${3kanollq4wk7zzoti4oim6e8vbsyuinpkcahgqtmt4n8bnckp6jg36mzb6ik2fxz  }
      PLATFORM_API_URL: ${PLATFORM_API_URL}
      MONGO_HOST: mongo
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27027:27017
    volumes:
      - ${DATA_DIRECTORY}/mongo/data:/data/db
